import type { createTranslator } from "@/lib/i18n/messages";
import type { PollSectionLabels } from "@/features/polls/components/pollFormSection";
import {
    POLL_MAX_OPTIONS,
    POLL_MIN_OPTIONS,
} from "@/features/polls/schemas/pollSchema";

/** 관리자 공지 작성은 한국어 화면이라 라벨을 여기 둔다(편집기 라벨과 같은 방식) */
export const ANNOUNCEMENT_POLL_LABELS: PollSectionLabels = {
    section: "투표",
    optional: "선택",
    create: "투표 만들기",
    edit: "고치기",
    remove: "지우기",
    title: "투표",
    question: "질문",
    options: "선택지",
    addOption: "선택지 추가",
    pasteOptions: "여러 줄 붙여넣기",
    pasteHelp: "한 줄에 하나씩 넣으면 선택지로 나뉩니다.",
    optionHelp: `엔터를 치면 아래에 칸이 하나 생깁니다 · ${POLL_MIN_OPTIONS}~${POLL_MAX_OPTIONS}개`,
    removeOption: "선택지 지우기",
    choiceWay: "고르는 방법",
    single: "한 개만",
    multiple: "여러 개",
    maxChoices: "최대 몇 개까지",
    voters: "누가 무엇을 골랐는지",
    votersHidden: "숨김",
    votersShown: "보임",
    advanced: "자세히",
    closesAt: "마감",
    closesHelp: "비우면 마감 없이 계속 받습니다.",
    results: "결과 공개",
    resultOptions: {
        ALWAYS: "항상",
        AFTER_VOTE: "투표한 뒤",
        AFTER_CLOSE: "마감한 뒤",
    },
    allowAddOptions: "게시한 뒤에도 선택지를 더할 수 있게",
    cancel: "취소",
    submit: "넣기",
    locked: "표가 들어와 질문과 선택지는 고칠 수 없습니다. 마감 시각만 바꿀 수 있습니다.",
    errors: {
        question: "질문을 입력해주세요.",
        options: `선택지를 ${POLL_MIN_OPTIONS}개 이상 ${POLL_MAX_OPTIONS}개 이하로 입력해주세요.`,
        duplicate: "같은 선택지를 두 번 넣을 수 없습니다.",
        maxChoices: "최대 개수를 다시 확인해주세요.",
        closesAt: "마감은 지금보다 뒤여야 합니다.",
    },
    localeLabels: { ko: "한국어", ja: "日本語", en: "English" },
    summaryOptions: (count) => `선택지 ${count}개`,
    summarySingle: "한 개만 고름",
    summaryMultiple: "여러 개 고름",
    summaryCloses: (date) => `${date} 마감`,
    summaryNoClose: "마감 없음",
    votes: (count) => `${count.toLocaleString("ko-KR")}표`,
};

/** 이벤트 글쓰기는 보는 언어로 — 화면 말 사전에서 라벨을 만든다 */
export function pollLabelsFrom(
    t: ReturnType<typeof createTranslator>
): PollSectionLabels {
    return {
        section: t("poll.section"),
        optional: t("poll.optional"),
        create: t("poll.create"),
        edit: t("poll.edit"),
        remove: t("poll.remove"),
        title: t("poll.title"),
        question: t("poll.question"),
        options: t("poll.options"),
        addOption: t("poll.addOption"),
        pasteOptions: t("poll.pasteOptions"),
        pasteHelp: t("poll.pasteHelp"),
        optionHelp: t("poll.optionHelp", {
            min: POLL_MIN_OPTIONS,
            max: POLL_MAX_OPTIONS,
        }),
        removeOption: t("poll.removeOption"),
        choiceWay: t("poll.choiceWay"),
        single: t("poll.single"),
        multiple: t("poll.multiple"),
        maxChoices: t("poll.maxChoices"),
        voters: t("poll.voters"),
        votersHidden: t("poll.votersHidden"),
        votersShown: t("poll.votersShown"),
        advanced: t("poll.advanced"),
        closesAt: t("poll.closesAt"),
        closesHelp: t("poll.closesHelp"),
        results: t("poll.results"),
        resultOptions: {
            ALWAYS: t("poll.results.ALWAYS"),
            AFTER_VOTE: t("poll.results.AFTER_VOTE"),
            AFTER_CLOSE: t("poll.results.AFTER_CLOSE"),
        },
        allowAddOptions: t("poll.allowAddOptions"),
        cancel: t("poll.cancel"),
        submit: t("poll.submit"),
        locked: t("poll.locked"),
        errors: {
            question: t("poll.error.question"),
            options: t("poll.error.options"),
            duplicate: t("poll.error.duplicate"),
            maxChoices: t("poll.error.maxChoices"),
            closesAt: t("poll.error.closesAt"),
        },
        summaryOptions: (count) => t("poll.summary.options", { count }),
        summarySingle: t("poll.summary.single"),
        summaryMultiple: t("poll.summary.multiple"),
        summaryCloses: (date) => t("poll.summary.closes", { date }),
        summaryNoClose: t("poll.summary.noClose"),
        votes: (count) => t("poll.summary.votes", { count }),
    };
}
