import "server-only";
import db from "@/lib/db";
import { syncStatusSchema } from "@/features/sync/schemas/syncStatusSchema";

// Classify only diagnostics generated by the existing ingestion pipeline. Never
// return an internal diagnostic or infer an official-session/token failure.
export function classifySyncAttempt(
    sync: { status: string; error_message: string | null; started_at: Date },
    now: Date
) {
    if (sync.status === "processing") {
        const age = now.getTime() - sync.started_at.getTime();
        return age >= 900000
            ? "timedOut"
            : age >= 600000
              ? "delayed"
              : "processing";
    }
    if (sync.status === "completed")
        return sync.error_message ? "partial" : "completed";
    return sync.error_message === "동기화 처리 시간이 초과되었습니다."
        ? "timedOut"
        : "failed";
}

export async function getSyncStatus(userId: number, now = new Date()) {
    const [attempts, played, judgement, timing] = await Promise.all([
        db.dataSync.findMany({
            where: { user_id: userId },
            orderBy: [{ started_at: "desc" }, { id: "desc" }],
            take: 5,
            select: {
                id: true,
                status: true,
                sync_scope: true,
                received_plays: true,
                inserted_plays: true,
                changed_records: true,
                error_message: true,
                started_at: true,
                completed_at: true,
            },
        }),
        db.musicChart.count({
            where: {
                OR: [
                    {
                        PlayData: {
                            some: { user_id: userId, play_count: { gt: 0 } },
                        },
                    },
                    { playHistory: { some: { user_id: userId } } },
                ],
            },
        }),
        db.musicChart.count({
            where: {
                OR: [
                    {
                        PlayData: {
                            some: {
                                user_id: userId,
                                play_count: { gt: 0 },
                                judge_sjust: { not: null },
                                judge_just: { not: null },
                                judge_good: { not: null },
                                judge_miss: { not: null },
                                judge_near: { not: null },
                            },
                        },
                    },
                    {
                        playHistory: {
                            some: {
                                user_id: userId,
                                judge_sjust: { not: null },
                                judge_just: { not: null },
                                judge_good: { not: null },
                                judge_miss: { not: null },
                                judge_near: { not: null },
                            },
                        },
                    },
                ],
            },
        }),
        db.chartPlayHistory.groupBy({
            by: ["chart_id"],
            where: {
                user_id: userId,
                fast_count: { not: null },
                slow_count: { not: null },
            },
        }),
    ]);
    const recordCounts = await db.chartRecordSnapshot.groupBy({
        by: ["sync_id"],
        where: {
            user_id: userId,
            sync_id: {
                in: attempts
                    .filter(
                        (attempt) =>
                            attempt.sync_scope === "full" &&
                            attempt.status === "completed"
                    )
                    .map((attempt) => attempt.id),
            },
            play_count: { gt: 0 },
        },
        _count: { _all: true },
    });
    const playedChanges = new Map(
        recordCounts.map((row) => [row.sync_id, row._count._all])
    );
    const latest = attempts[0];
    const full = latest?.sync_scope === "full";
    const firstFullImport = Boolean(
        latest?.status === "completed" &&
        full &&
        (playedChanges.get(latest.id) ?? 0) > 3 &&
        !(await db.dataSync.findFirst({
            where: {
                user_id: userId,
                status: "completed",
                sync_scope: "full",
                id: { not: latest.id },
                started_at: { lte: latest.started_at },
            },
            select: { id: true },
        }))
    );
    const chart = {
        select: {
            music_idx: true,
            difficulty: true,
            level: true,
            music: { select: { title: true } },
        },
    } as const;
    const changes =
        latest?.status !== "completed" || firstFullImport
            ? []
            : full
              ? await db.chartRecordSnapshot.findMany({
                    where: {
                        user_id: userId,
                        sync_id: latest.id,
                        play_count: { gt: 0 },
                    },
                    orderBy: { id: "desc" },
                    take: 3,
                    select: { score: true, chart },
                })
              : await db.chartPlayHistory.findMany({
                    where: { user_id: userId, first_sync_id: latest.id },
                    orderBy: { id: "desc" },
                    take: 3,
                    select: { score: true, chart },
                });
    return syncStatusSchema.parse({
        observedAt: now.toISOString(),
        attempts: attempts.map((sync) => {
            const excluded =
                /^DB에 등록되지 않은 채보 (\d+)개를 건너뛰었습니다:/.exec(
                    sync.error_message ?? ""
                );
            return {
                id: sync.id,
                status: classifySyncAttempt(sync, now),
                scope: sync.sync_scope === "full" ? "full" : "recent",
                startedAt: sync.started_at.toISOString(),
                completedAt: sync.completed_at?.toISOString() ?? null,
                receivedPlays: sync.received_plays,
                insertedPlays: sync.inserted_plays,
                changedRecords:
                    sync.sync_scope === "full"
                        ? (playedChanges.get(sync.id) ?? 0)
                        : 0,
                excludedCount: excluded ? Number(excluded[1]) : null,
            };
        }),
        coverage: { played, judgement, timing: timing.length },
        firstFullImport,
        previews: changes.map(({ score, chart }) => ({
            score,
            musicId: chart.music_idx,
            title: chart.music.title,
            difficulty: chart.difficulty,
            level: chart.level,
        })),
        retryAfter: latest
            ? Math.max(
                  0,
                  Math.min(
                      30,
                      Math.ceil(
                          (30000 -
                              (now.getTime() - latest.started_at.getTime())) /
                              1000
                      )
                  )
              )
            : 0,
    });
}
